name: Build Artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create file
        run: echo "Build from GitHub Actions" > build.txt

      - name: Show file
        run: cat build.txt
