name: Build Artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create file
        run: echo "Build from GitHub Actions" > build.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-file
          path: build.txt
